CREATE TABLE guest (
	id INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	name VARCHAR(100),
	credit_card VARCHAR(50),
	vip INTEGER(1),
	room_id INTEGER
);

CREATE TABLE room (
	id INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	room_type INTEGER,
	beds INTEGER,
	sea_view INTEGER(1),
	note VARCHAR(200)	
};
