DROP TABLE IF EXISTS room;
CREATE TABLE room (
	id INTEGER NOT NULL AUTO_INCREMENT,
	type INTEGER,
	beds SMALLINT,
	seaview BOOLEAN,
	note VARCHAR(200),
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS guest;
CREATE TABLE guest (
	id INTEGER NOT NULL AUTO_INCREMENT,
	name VARCHAR(100),
	credit_card VARCHAR(50),
	vip BOOLEAN,
	room_id INTEGER,
	PRIMARY KEY (id),
	FOREIGN KEY (room_id) REFERENCES room (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci;