/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.muni.fi.pv168.hotel.gui;

import cz.muni.fi.pv168.hotel.Guest;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author wintermute
 */
public class GuestFrame extends javax.swing.JFrame {
    private static final ResourceBundle texts = ResourceBundle.getBundle("texts");
    
    private GuestTableModel guestModel;

    /**
     * Creates new form GuestFrame
     */
    public GuestFrame(GuestTableModel guestModel) {
        initComponents();
        this.guestModel = guestModel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextFieldName = new javax.swing.JTextField();
        jLabelName = new javax.swing.JLabel();
        jLabelCreditCard = new javax.swing.JLabel();
        jTextFieldCreditCard = new javax.swing.JTextField();
        jLabelVip = new javax.swing.JLabel();
        jRadioButtonVipYes = new javax.swing.JRadioButton();
        jRadioButtonVipNo = new javax.swing.JRadioButton();
        jButtonSave = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(texts.getString("ADD NEW GUEST")); // NOI18N
        setBackground(new java.awt.Color(238, 238, 138));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jTextFieldName.setToolTipText(texts.getString("NAME OF GUEST")); // NOI18N

        jLabelName.setText(texts.getString("NAME :")); // NOI18N

        jLabelCreditCard.setText(texts.getString("CREDITCARD :")); // NOI18N

        jTextFieldCreditCard.setToolTipText(texts.getString("8 DIGITS")); // NOI18N

        jLabelVip.setText(texts.getString("VIP :")); // NOI18N

        buttonGroup1.add(jRadioButtonVipYes);
        jRadioButtonVipYes.setText(texts.getString("YES")); // NOI18N
        jRadioButtonVipYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonVipYesActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonVipNo);
        jRadioButtonVipNo.setSelected(true);
        jRadioButtonVipNo.setText(texts.getString("NO")); // NOI18N

        jButtonSave.setText(texts.getString("SAVE")); // NOI18N
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonCancel.setText(texts.getString("CANCEL")); // NOI18N
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelCreditCard)
                            .addComponent(jLabelName)
                            .addComponent(jLabelVip))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonVipYes)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jRadioButtonVipNo)
                                .addComponent(jTextFieldCreditCard, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancel)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCreditCard)
                    .addComponent(jTextFieldCreditCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVip)
                    .addComponent(jRadioButtonVipYes)
                    .addComponent(jRadioButtonVipNo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonCancel))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonVipYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonVipYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonVipYesActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        String name = jTextFieldName.getText();
        String creditCard = jTextFieldCreditCard.getText();
        
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, texts.getString("YOU HAVE TO ENTER THE NAME."), texts.getString("NAME REQUIRED"), JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (creditCard.isEmpty()) {
            JOptionPane.showMessageDialog(this, texts.getString("YOU HAVE TO ENTER THE NUMBER OF CREDIT CARD."), texts.getString("CREDIT CARD REQUIRED"), JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Guest guest = new Guest();
        guest.setName(name);
        guest.setCreditCard(creditCard);
        guest.setVip(jRadioButtonVipYes.isSelected());
        
        guestModel.addRow(guest);
        
        this.dispose();
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabelCreditCard;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelVip;
    private javax.swing.JRadioButton jRadioButtonVipNo;
    private javax.swing.JRadioButton jRadioButtonVipYes;
    private javax.swing.JTextField jTextFieldCreditCard;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
}
