/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.muni.fi.pv168.hotel.gui;

import cz.muni.fi.pv168.hotel.RoomType;
import java.util.ResourceBundle;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author livthomas
 */
public class HotelFrame extends javax.swing.JFrame {
    private static final ResourceBundle texts = ResourceBundle.getBundle("texts");
    
    private GuestTableModel guestModel;
    private RoomTableModel roomModel;

    /**
     * Creates new form HotelFrame
     */
    public HotelFrame() {
        initComponents();
        
        guestModel = (GuestTableModel) jTableGuests.getModel();
        roomModel = (RoomTableModel) jTableRooms.getModel();
    }
    
    private void showGuestFrame() {
        GuestFrame guestFrame = new GuestFrame(guestModel);
        guestFrame.setVisible(true);
    }
    
    private void showRoomFrame() {
        RoomFrame roomFrame = new RoomFrame(roomModel);
        roomFrame.setVisible(true);
    }
    
    private void showCheckFrame() {
        int row = jTableGuests.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, texts.getString("YOU HAVE TO SELECT A GUEST."), texts.getString("CANNOT CHECK IN"), JOptionPane.WARNING_MESSAGE);
            return;
        }
        CheckFrame checkFrame = new CheckFrame(guestModel.getRow(row));
        if (checkFrame.getModel().isChecked()) {
            JOptionPane.showMessageDialog(this, texts.getString("THE GUEST HAS ALREADY BEEN CHECKED IN."), texts.getString("CANNOT CHECK IN"), JOptionPane.WARNING_MESSAGE);
            return;
        }
        checkFrame.setVisible(true);
    }
    
    private void actionDeleteGuest() {
        int row = jTableGuests.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, texts.getString("YOU HAVE TO SELECT A GUEST."), texts.getString("CANNOT DELETE GUEST"), JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (JOptionPane.showConfirmDialog(this, texts.getString("DO YOU REALLY WANT TO DELETE THE SELECTED GUEST?"), texts.getString("DELETE GUEST"), JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            guestModel.removeRow(row);
        }
    }
    
    private void actionDeleteRoom() {
        int row = jTableRooms.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, texts.getString("YOU HAVE TO SELECT A ROOM."), texts.getString("CANNOT DELETE ROOM"), JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (JOptionPane.showConfirmDialog(this, texts.getString("DO YOU REALLY WANT TO DELETE THE SELECTED ROOM?"), texts.getString("DELETE ROOM"), JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            roomModel.removeRow(row);
        }
    }
    
    private void actionCheckOut() {
        int row = jTableGuests.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, texts.getString("YOU HAVE TO SELECT A GUEST."), texts.getString("CANNOT CHECK OUT"), JOptionPane.WARNING_MESSAGE);
            return;
        }
        CheckTableModel checkModel = new CheckTableModel(guestModel.getRow(row));
        if (!checkModel.isChecked()) {
            JOptionPane.showMessageDialog(this, texts.getString("THE GUEST HAS NOT BEEN CHECKED IN."), texts.getString("CANNOT CHECK OUT"), JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (JOptionPane.showConfirmDialog(this, texts.getString("DO YOU REALLY WANT TO CHECK THE SELECTED GUEST OUT?"), texts.getString("CHECK OUT GUEST"), JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            checkModel.checkOut();
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        jScrollPaneGuest = new javax.swing.JScrollPane();
        jTableGuests = new javax.swing.JTable();
        jScrollPaneRoom = new javax.swing.JScrollPane();
        jTableRooms = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonAddGuest = new javax.swing.JButton();
        jButtonDeleteGuest = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jButtonAddRoom = new javax.swing.JButton();
        jButtonDeleteRoom = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButtonCheckIn = new javax.swing.JButton();
        jButtonCheckOut = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        addGuestMenuItem = new javax.swing.JMenuItem();
        jMenuItemDeleteGuest = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        addRoomMenuItem = new javax.swing.JMenuItem();
        jMenuItemDeleteRoom = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItemCheckIn = new javax.swing.JMenuItem();
        jMenuItemCheckOut = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(texts.getString("HOTEL MANAGER")); // NOI18N

        jTabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPaneStateChanged(evt);
            }
        });

        jTableGuests.setModel(new GuestTableModel());
        jTableGuests.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableGuests.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTableGuestsFocusGained(evt);
            }
        });
        jScrollPaneGuest.setViewportView(jTableGuests);

        jTabbedPane.addTab(texts.getString("GUESTS"), jScrollPaneGuest); // NOI18N

        jTableRooms.setModel(new RoomTableModel());
        JComboBox roomTypeComboBox = new JComboBox(RoomType.values());
        jTableRooms.getColumnModel().getColumn(1).setCellEditor(new DefaultCellEditor(roomTypeComboBox));
        jTableRooms.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTableRoomsFocusGained(evt);
            }
        });
        jScrollPaneRoom.setViewportView(jTableRooms);
        //JComboBox typeComboBox = new JComboBox();
        //for (RoomType type : RoomType.values()) {
            //    typeComboBox.addItem(type);
            //}
        //jTableRooms.getColumnModel().getColumn(1).setCellEditor(new DefaultCellEditor(typeComboBox));

        jTabbedPane.addTab(texts.getString("ROOMS"), jScrollPaneRoom); // NOI18N

        jToolBar1.setRollover(true);

        jButtonAddGuest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_add.png"))); // NOI18N
        jButtonAddGuest.setText(texts.getString("ADD GUEST")); // NOI18N
        jButtonAddGuest.setFocusable(false);
        jButtonAddGuest.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonAddGuest.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAddGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddGuestActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonAddGuest);

        jButtonDeleteGuest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_delete.png"))); // NOI18N
        jButtonDeleteGuest.setText(texts.getString("DELETE GUEST")); // NOI18N
        jButtonDeleteGuest.setEnabled(false);
        jButtonDeleteGuest.setFocusable(false);
        jButtonDeleteGuest.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonDeleteGuest.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonDeleteGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteGuestActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonDeleteGuest);
        jToolBar1.add(jSeparator4);

        jButtonAddRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/key_add.png"))); // NOI18N
        jButtonAddRoom.setText(texts.getString("ADD ROOM")); // NOI18N
        jButtonAddRoom.setFocusable(false);
        jButtonAddRoom.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonAddRoom.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAddRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddRoomActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonAddRoom);

        jButtonDeleteRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/key_delete.png"))); // NOI18N
        jButtonDeleteRoom.setText(texts.getString("DELETE ROOM")); // NOI18N
        jButtonDeleteRoom.setEnabled(false);
        jButtonDeleteRoom.setFocusable(false);
        jButtonDeleteRoom.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonDeleteRoom.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonDeleteRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteRoomActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonDeleteRoom);
        jToolBar1.add(jSeparator2);

        jButtonCheckIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/book_add.png"))); // NOI18N
        jButtonCheckIn.setText(texts.getString("CHECK IN")); // NOI18N
        jButtonCheckIn.setEnabled(false);
        jButtonCheckIn.setFocusable(false);
        jButtonCheckIn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonCheckIn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckInActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonCheckIn);

        jButtonCheckOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/book_delete.png"))); // NOI18N
        jButtonCheckOut.setText(texts.getString("CHECK OUT")); // NOI18N
        jButtonCheckOut.setEnabled(false);
        jButtonCheckOut.setFocusable(false);
        jButtonCheckOut.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonCheckOut.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckOutActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonCheckOut);

        fileMenu.setMnemonic('f');
        fileMenu.setText(texts.getString("HOTEL")); // NOI18N

        addGuestMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        addGuestMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_add.png"))); // NOI18N
        addGuestMenuItem.setMnemonic('o');
        addGuestMenuItem.setText(texts.getString("ADD GUEST")); // NOI18N
        addGuestMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGuestMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(addGuestMenuItem);

        jMenuItemDeleteGuest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_delete.png"))); // NOI18N
        jMenuItemDeleteGuest.setText(texts.getString("DELETE GUEST")); // NOI18N
        jMenuItemDeleteGuest.setEnabled(false);
        jMenuItemDeleteGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeleteGuestActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItemDeleteGuest);
        fileMenu.add(jSeparator5);

        addRoomMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        addRoomMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/key_add.png"))); // NOI18N
        addRoomMenuItem.setMnemonic('s');
        addRoomMenuItem.setText(texts.getString("ADD ROOM")); // NOI18N
        addRoomMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRoomMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(addRoomMenuItem);

        jMenuItemDeleteRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/key_delete.png"))); // NOI18N
        jMenuItemDeleteRoom.setText(texts.getString("DELETE ROOM")); // NOI18N
        jMenuItemDeleteRoom.setEnabled(false);
        jMenuItemDeleteRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeleteRoomActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItemDeleteRoom);
        fileMenu.add(jSeparator3);

        jMenuItemCheckIn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCheckIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/book_add.png"))); // NOI18N
        jMenuItemCheckIn.setText(texts.getString("CHECK IN")); // NOI18N
        jMenuItemCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCheckInActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItemCheckIn);

        jMenuItemCheckOut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCheckOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/book_delete.png"))); // NOI18N
        jMenuItemCheckOut.setText(texts.getString("CHECK OUT")); // NOI18N
        jMenuItemCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCheckOutActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItemCheckOut);
        fileMenu.add(jSeparator1);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/door_in.png"))); // NOI18N
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText(texts.getString("EXIT")); // NOI18N
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void addGuestMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGuestMenuItemActionPerformed
        showGuestFrame();
    }//GEN-LAST:event_addGuestMenuItemActionPerformed

    private void addRoomMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRoomMenuItemActionPerformed
        showRoomFrame();
    }//GEN-LAST:event_addRoomMenuItemActionPerformed

    private void jButtonAddGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddGuestActionPerformed
        showGuestFrame();
    }//GEN-LAST:event_jButtonAddGuestActionPerformed

    private void jButtonAddRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddRoomActionPerformed
        showRoomFrame();
    }//GEN-LAST:event_jButtonAddRoomActionPerformed

    private void jButtonDeleteGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteGuestActionPerformed
        actionDeleteGuest();
    }//GEN-LAST:event_jButtonDeleteGuestActionPerformed

    private void jMenuItemDeleteGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeleteGuestActionPerformed
        actionDeleteGuest();
    }//GEN-LAST:event_jMenuItemDeleteGuestActionPerformed

    private void jTableGuestsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTableGuestsFocusGained
        jButtonDeleteGuest.setEnabled(true);
        jMenuItemDeleteGuest.setEnabled(true);
        jButtonCheckIn.setEnabled(true);
        jMenuItemCheckIn.setEnabled(true);
        jButtonCheckOut.setEnabled(true);
        jMenuItemCheckOut.setEnabled(true);
    }//GEN-LAST:event_jTableGuestsFocusGained

    private void jTableRoomsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTableRoomsFocusGained
        jButtonDeleteRoom.setEnabled(true);
        jMenuItemDeleteRoom.setEnabled(true);
    }//GEN-LAST:event_jTableRoomsFocusGained

    private void jTabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPaneStateChanged
        if (jTabbedPane.getSelectedIndex() == 0) {
            jButtonDeleteRoom.setEnabled(false);
            jMenuItemDeleteRoom.setEnabled(false);
        } else {
            jButtonDeleteGuest.setEnabled(false);
            jMenuItemDeleteGuest.setEnabled(false);
            jButtonCheckIn.setEnabled(false);
            jMenuItemCheckIn.setEnabled(false);
            jButtonCheckOut.setEnabled(false);
            jMenuItemCheckOut.setEnabled(false);
        }
    }//GEN-LAST:event_jTabbedPaneStateChanged

    private void jButtonDeleteRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteRoomActionPerformed
        actionDeleteRoom();
    }//GEN-LAST:event_jButtonDeleteRoomActionPerformed

    private void jMenuItemDeleteRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeleteRoomActionPerformed
        actionDeleteRoom();
    }//GEN-LAST:event_jMenuItemDeleteRoomActionPerformed

    private void jButtonCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckInActionPerformed
        showCheckFrame();
    }//GEN-LAST:event_jButtonCheckInActionPerformed

    private void jMenuItemCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCheckInActionPerformed
        showCheckFrame();
    }//GEN-LAST:event_jMenuItemCheckInActionPerformed

    private void jButtonCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckOutActionPerformed
        actionCheckOut();
    }//GEN-LAST:event_jButtonCheckOutActionPerformed

    private void jMenuItemCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCheckOutActionPerformed
        actionCheckOut();
    }//GEN-LAST:event_jMenuItemCheckOutActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if (texts.getString("NIMBUS").equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HotelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HotelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HotelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HotelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new HotelFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addGuestMenuItem;
    private javax.swing.JMenuItem addRoomMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton jButtonAddGuest;
    private javax.swing.JButton jButtonAddRoom;
    private javax.swing.JButton jButtonCheckIn;
    private javax.swing.JButton jButtonCheckOut;
    private javax.swing.JButton jButtonDeleteGuest;
    private javax.swing.JButton jButtonDeleteRoom;
    private javax.swing.JMenuItem jMenuItemCheckIn;
    private javax.swing.JMenuItem jMenuItemCheckOut;
    private javax.swing.JMenuItem jMenuItemDeleteGuest;
    private javax.swing.JMenuItem jMenuItemDeleteRoom;
    private javax.swing.JScrollPane jScrollPaneGuest;
    private javax.swing.JScrollPane jScrollPaneRoom;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable jTableGuests;
    private javax.swing.JTable jTableRooms;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables
}
